ASoC: SOF: imx: fix compilation with allyesconfig
make ARCH=mips allyesconfig generates this error:

sound/soc/sof/imx/imx8m.o:(.data.dsp_ops+0x0): multiple definition of
`dsp_ops'
sound/soc/sof/imx/imx8.o:(.data.dsp_ops+0x0): first defined here

Fix by making the definitions static

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Pierre-Louis Bossart <pierre-louis.bossart@linux.intel.com>
(cherry picked from commit 1a6caa2891ad73f294b2f6800c292f66a4ac8516)
Signed-off-by: Hui Wang <hui.wang@canonical.com>